### PR TITLE
Update PrefabBrush and PrefabRandomBrush

### PR DESCRIPTION
**Pull request by RyotaMurohoshi**
In this PR,

* updated [2d-extras](https://github.com/Unity-Technologies/2d-extras) revision to ab1eea681b79ce7c5abeac5631a4dc54ee34c649.
* updated and fixed `Example Prefab Brush` with new SerializedBinary.
* added new `Example Prefab Random Brush`.

* Updated `Example Prefab Brush` paints Blue circle SpriteRenderer Prefab.
* New  `Example Prefab Random Brush` paints Red, Green and Blue circle SpriteRenderer Prefabs randomly.

スクリーンショット 2020-05-21 2 22 03

### CODE REVIEW

**Comment by ChuanXin-Unity** [comment]
Great work adding the examples for the Prefab Brush!

**Comment by ChuanXin-Unity** [comment]
The colors for the Blue and Green Prefabs are swapped, let's see if they can be edited!

**Comment by ChuanXin-Unity** [comment]
Would you like me to merge this in and edit it later? Thanks!

**Comment by RyotaMurohoshi** [comment]
Oh!
Sorry I fixed it. 🙇

**Comment by ChuanXin-Unity** [comment]
Thanks for working on this so fast!

**Pull request merged**
